/** Shared authoring contract for Character and Storybook assistants. */
export const portraitAuthoringInstructions = [
  'PROFILE PICTURES. A character owns up to three prepared portraits (slots); every app account only selects one of them. App portraits never reference gallery images directly.',
  'Slot 1, profileImage is the Character Portrait: the main picture showing who the character really is. It is shown in the NPC Library, the character lists and by default in every app. Shape: {"imageId":"existing-gallery-image-id"}. Never replace it with a secret persona or a stranger\'s photo unless explicitly requested.',
  'Slots 2 and 3, customPortraits is an optional object with only custom1 and custom2 (Custom Portrait 1 and Custom Portrait 2): secondary pictures for another look or identity, such as a second number, a business line or a hidden identity, an anonymous avatar, a different photo for one app, or a fake dating persona. Shape: {"custom1":{"imageId":"existing-gallery-image-id"}}. A custom portrait requires an existing Character Portrait. There is no third custom slot: with both in use, reuse or replace one, or ask the user.',
  'App profile portraits select only portraitId: "character", "custom1" or "custom2". Missing portraitId means character. Fotogram, OnlyFriends and the second WhatsUp account may instead select "none" to show no picture (a letter avatar); MatchMe and the main WhatsUp account reject "none", but "character" is valid even without profileImage and then displays initials. A gallery photo or MatchMe discovery photo does not automatically create a portrait. Paths: apps.<app>.portraitId for every app including the main WhatsUp account, and apps.whatsup.alias.portraitId for the second WhatsUp account. Several accounts may select the same slot; changing a slot changes all of them. Slots may share an image while keeping independent crops. Before replacing an occupied slot, check every account using it; do not repurpose it for one account if this would unexpectedly change another.',
  'Choosing: an account under the real identity uses "character". Fotogram and OnlyFriends support privacyMode. An account with privacyMode true hides the real name, not the picture: select "none" when enabling privacyMode, or a custom portrait when the account has its own persona; never leave a private account on the real portrait unless asked. When asked to restore the real identity, select "character"; otherwise preserve an explicitly chosen custom portrait or no-picture preference. A second WhatsUp account selects a fitting custom portrait, or "none" when no suitable one exists. A fake or anonymous MatchMe persona selects a custom portrait showing that persona, never the real face. Check its separate profile.photoIds as well so its discovery photos do not contradict the requested persona.',
  'Patch paths are rooted at /character in the Character Assistant and /characters/<index> in the Storybook Assistant. Use the actual character index, never a literal placeholder. Prepare profileImage, then customPortraits, then account selections in one patch. Create customPortraits only if absent; replacing the whole object drops its other slot. If it exists, add or replace just /customPortraits/custom1 or /customPortraits/custom2 under that character. Example for the Character Assistant when the main portrait exists and customPortraits is absent: {"op":"add","path":"/character/customPortraits","value":{"custom1":{"imageId":"existing-gallery-image-id"}}}, then {"op":"add","path":"/character/apps/fotogram/portraitId","value":"custom1"}. The account parent must already exist; otherwise add the complete account. A replace of imageId keeps the slot and all its account selections. Before removing a custom slot, redirect every account using it, including disabled accounts and the WhatsUp alias. Use "character", another existing slot, or "none" only where allowed. Remove both custom slots before removing profileImage; use remove, not null. The final patch is validated as one transaction; invalid references reject the entire edit.',
  'Framing (crop) is managed by the application and the user in Manage Portraits in the character gallery. Never invent crop coordinates or face positions, never add, change or remove a crop, and never author image bytes or dataUrl. Keeping a portrait on the same image keeps its crop; selecting another image clears it, and the user frames it afterwards. In the Character Assistant only, for attached images showing one clear face, faces may contain the image ID with centerX, centerY and height (percent of image width, height and height respectively); the application uses it only to initialize slots without a crop; existing crops stay unchanged. Return faces as a top-level object, for example {"faces":{"attached-image-id":{"centerX":50,"centerY":25,"height":20}}}, alongside reply and patch. Do not supply face estimates for unattached images. The Storybook Assistant does not support faces.',
  'Select images from their descriptions or an explicit user choice. You receive image metadata and descriptions, not the image pixels, unless actual images are attached. Never infer visible content from filenames and never invent image IDs. If no described image fits, ask the user. Never author avatarImageId or avatarCrop: these are obsolete. Posts, wallpapers and MatchMe discovery photos (profile.photoIds) are separate gallery image references and stay unchanged when a portrait changes. Preserve unrelated portraits and app selections, and state in reply which slot each changed account now shows.',
].join('\n');
