/** Shared authoring contract for Character and Storybook assistants. */
export const portraitAuthoringInstructions = [
  'PROFILE PICTURES. A character owns up to three prepared portraits (slots); every app account only selects one of them. Apps never reference gallery images directly.',
  'Slot 1, profileImage is the Character Portrait: the main picture showing who the character really is. It is shown in the NPC Library, the character lists and by default in every app. Shape: {"imageId":"existing-gallery-image-id"}. Never replace it with a secret persona or a stranger\'s photo unless explicitly requested.',
  'Slots 2 and 3, customPortraits is an optional object with only custom1 and custom2 (Custom Portrait 1 and Custom Portrait 2): secondary pictures for another look or identity, such as a second number, a business line or a hidden identity, an anonymous avatar, a different photo for one app, or a fake dating persona. Shape: {"custom1":{"imageId":"existing-gallery-image-id"}}. A custom portrait requires an existing Character Portrait. There is no third custom slot: with both in use, reuse or replace one, or ask the user.',
  'App profile portraits select only portraitId: "character", "custom1" or "custom2". Missing portraitId means character. Fotogram, OnlyFriends and the second WhatsUp account may instead select "none" to show no picture (a letter avatar); MatchMe and the main WhatsUp account always require a portrait and reject "none". Paths: apps.<app>.portraitId for every app including the main WhatsUp account, and apps.whatsup.alias.portraitId for the second WhatsUp account. Several accounts may select the same slot; changing a slot changes all of them.',
  'Choosing: an account under the real identity uses "character". An account with privacyMode true hides the real name, not the picture: select "none" when enabling privacyMode, or a custom portrait when the account has its own persona; never leave a private account on the real portrait unless asked. When privacyMode is switched off again, change "none" back to "character". A second WhatsUp account selects a fitting custom portrait, or "none" when no suitable one exists. A fake or anonymous MatchMe persona selects a custom portrait showing that persona, never the real face.',
  'Order of operations in one patch: first the Character Portrait, then the custom slot, then the accounts selecting it. A custom slot must exist before any portraitId selects it. Create the customPortraits parent with add before patching a child, for example {"op":"add","path":".../customPortraits","value":{"custom1":{"imageId":"image-id"}}} followed by {"op":"add","path":".../apps/matchme/portraitId","value":"custom1"}. Before removing a custom slot, set every account selecting it to "character" or "none" in the same patch. Remove both custom slots before removing the Character Portrait. Selecting a missing slot is rejected and nothing is saved.',
  'Framing (crop) is managed by the application and the user in Manage Portraits in the character gallery. Never invent crop coordinates or face positions, never add or change a crop, and never author image bytes or dataUrl. Keeping a portrait on the same image keeps its crop; selecting another image clears it, and the user frames it afterwards. In the Character Assistant only, for attached images showing one clear face, faces may contain the image ID with centerX, centerY and height (percent of image width, height and height respectively); the application applies it to every slot using that image.',
  'Select images from their descriptions or an explicit user choice. You receive image metadata and descriptions, not the image pixels, unless actual images are attached. Never infer visible content from filenames and never invent image IDs. If no described image fits, ask the user. Never author avatarImageId or avatarCrop: these are obsolete. Posts, wallpapers and MatchMe discovery photos (profile.photoIds) are separate gallery image references and stay unchanged when a portrait changes. Preserve unrelated portraits and app selections, and state in reply which slot each changed account now shows.',
].join('\n');
