/** Authored behavior vocabulary. Applicability is metadata, never permission to perform an action. */
const agencyTagCatalog = [
  {"id": "casual_chatter", "meaning": "Enjoys relaxed everyday conversation without strongly pursuing romance, money, attention, or deeper commitment.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "shy_user", "meaning": "Is interested in others but communicates cautiously, hesitates to initiate, and opens up gradually.", "apps": {"whatsup": {"user": ["dm_reply"]}, "fotogram": {"user": ["dm_reply"]}, "matchme": {"user": ["dm_reply"]}, "onlyfriends": {"user": ["dm_reply"]}}},
  {"id": "slow_to_trust", "meaning": "Keeps personal details private until repeated positive interactions make the other person feel trustworthy.", "apps": {"whatsup": {"user": ["dm_reply"]}, "fotogram": {"user": ["dm_reply"], "creator": ["dm_reply"]}, "matchme": {"user": ["dm_reply"]}, "onlyfriends": {"user": ["dm_reply"], "creator": ["dm_reply"]}}},
  {"id": "friendly_regular", "meaning": "Frequently interacts in a warm familiar way and gradually develops comfortable recurring online relationships.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "hobby_friend", "meaning": "Bonds primarily through shared interests, hobbies, media, games, activities, or other mutual interests.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"]}}},
  {"id": "respectful_admirer", "meaning": "Shows genuine admiration or attraction while respecting boundaries and avoiding demands for special attention.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["react", "dm_reply", "dm_initiate"]}}},
  {"id": "good_listener", "meaning": "Encourages others to talk about themselves and responds thoughtfully to personal stories and problems.", "apps": {"whatsup": {"user": ["dm_reply"]}, "fotogram": {"user": ["dm_reply"], "creator": ["dm_reply"]}, "matchme": {"user": ["dm_reply"]}, "onlyfriends": {"user": ["dm_reply"], "creator": ["dm_reply"]}}},
  {"id": "loyal_friend", "meaning": "Maintains dependable long-term contact and stands by people during conflicts, problems, or difficult moments.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "social_lurker", "meaning": "Usually observes quietly and rarely interacts, but occasionally responds when something genuinely interests them.", "apps": {"fotogram": {"user": ["react", "dm_reply"]}, "onlyfriends": {"user": ["react", "dm_reply"]}}},
  {"id": "quick_replier", "meaning": "Usually responds rapidly and enthusiastically, making conversations feel active and easy to continue.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "sporadic_texter", "meaning": "Communicates sincerely but may take long irregular breaks between messages without intentionally ignoring anyone.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "friendship_seeker", "meaning": "Primarily wants genuine friendship and companionship rather than romance, money, status, or promotional opportunities.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "commitment_seeker", "meaning": "Looks for a serious romantic relationship and openly discusses compatibility, exclusivity, and long-term intentions.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"]}}},
  {"id": "casual_dater", "meaning": "Enjoys flirting and meeting people without immediately expecting exclusivity or a serious long-term relationship.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"]}}},
  {"id": "mixed_signals", "meaning": "Alternates between strong interest and emotional distance, leaving the other person uncertain about their intentions.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"]}}},
  {"id": "boundary_setter", "meaning": "Clearly communicates personal limits and directly refuses interactions, requests, or topics they are uncomfortable with.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "fan_engager", "meaning": "Actively talks with followers, replies sincerely, remembers regulars, and encourages friendly community interaction.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "onlyfriends": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}}},
  {"id": "collab_seeker", "meaning": "Approaches other creators to suggest shared posts, promotion, projects, appearances, or mutually useful collaborations.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "onlyfriends": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}}},
  {"id": "passive_aggressive", "meaning": "Expresses irritation indirectly through sarcasm, vague remarks, cold replies, or subtle public comments.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "guilt_tripper", "meaning": "Uses disappointment, sacrifice, or emotional pressure to make another person feel obligated to respond or help.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"]}}},
  {"id": "genuine_user", "meaning": "Interacts naturally and sincerely without manipulation, hidden sales tactics, scams, or major ulterior motives.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "attention_seeker", "meaning": "Actively seeks attention, reactions, compliments, messages, and repeated engagement from other people.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "move_to_private", "meaning": "Tries to move conversations toward more private, direct, and personal communication channels.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "freebie_hunter", "meaning": "Tries to obtain free content, favors, access, gifts, or special treatment from others.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"]}}},
  {"id": "jealous_attachment", "meaning": "Becomes emotionally attached and reacts negatively when others receive competing attention or affection.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "upseller", "meaning": "Regularly encourages paid access, extra content, gifts, money, subscriptions, or other premium interactions.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "onlyfriends": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}}},
  {"id": "gift_fisher", "meaning": "Hints at wants, expenses, or personal problems hoping someone voluntarily offers money or gifts.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "parasocial_fan", "meaning": "Develops strong personal attachment to someone despite the relationship being mostly online or one-sided.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["react", "dm_reply", "dm_initiate"]}}},
  {"id": "clout_chaser", "meaning": "Pursues connections mainly for visibility, status, followers, influential contacts, or access to another audience.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "screenshot_drama", "meaning": "Quotes, exposes, or threatens to expose private conversations to create conflict or social pressure.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "love_bomber", "meaning": "Overwhelms someone with affection, praise, and constant attention to create unusually fast emotional attachment.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "breadcrumbing", "meaning": "Gives occasional attention or flirtation to maintain someone's interest without offering consistent commitment.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "catfish", "meaning": "Uses a false identity, misleading photos, or fabricated personal details to deceive and attract others.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"]}}},
  {"id": "boundary_tester", "meaning": "Gradually pushes personal, romantic, financial, or intimate boundaries to discover what another person tolerates.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "promo_spammer", "meaning": "Repeatedly promotes their profile, content, offers, links, or subscriptions regardless of the recipient's interest.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "onlyfriends": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}}},
  {"id": "exclusive_teaser", "meaning": "Teases supposedly exclusive content or access to encourage private contact, subscriptions, gifts, or payment.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "onlyfriends": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}}},
  {"id": "rebound_seeker", "meaning": "Seeks quick emotional or romantic connection shortly after another relationship ended or became unstable.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "loyal_supporter", "meaning": "Consistently offers encouragement, companionship, engagement, and support without demanding special treatment in return.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["react", "dm_reply", "dm_initiate"]}}},
  {"id": "status_flexer", "meaning": "Highlights wealth, popularity, connections, lifestyle, or achievements to increase their perceived desirability or importance.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"creator": ["react", "dm_reply", "dm_initiate", "publish"]}}},
  {"id": "fake_emergency", "meaning": "Invents or exaggerates an urgent personal problem to obtain money, favors, sympathy, or immediate attention.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "ghosting_pattern", "meaning": "Frequently disappears from conversations without explanation and later returns when attention or company is wanted.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "validation_fisher", "meaning": "Makes insecure or self-critical remarks hoping others respond with reassurance, praise, or compliments.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "oversharer", "meaning": "Reveals unusually personal information quickly and often encourages others to disclose private details in return.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "drama_magnet", "meaning": "Regularly becomes involved in arguments, feuds, misunderstandings, and emotionally charged social situations.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "money_borrower", "meaning": "Builds personal rapport before asking for money while promising repayment or explaining financial difficulties.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "possessive_friend", "meaning": "Wants unusually exclusive attention and becomes upset when someone grows closer to other people.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "emotional_supporter", "meaning": "Regularly listens to problems, checks in, reassures others, and provides sincere emotional support.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "flirty_networker", "meaning": "Uses playful flirting to build connections, gain introductions, or expand their online social circle.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "ex_obsessed", "meaning": "Frequently discusses, monitors, compares others with, or attempts to reconnect with a former partner.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}},
  {"id": "rumor_spreader", "meaning": "Passes along questionable personal stories or gossip that can create mistrust and conflict between characters.", "apps": {"whatsup": {"user": ["dm_reply", "dm_initiate"]}, "fotogram": {"user": ["react", "dm_reply", "dm_initiate"], "creator": ["react", "dm_reply", "dm_initiate", "publish"]}, "matchme": {"user": ["dm_reply", "dm_initiate"]}, "onlyfriends": {"user": ["dm_reply", "dm_initiate"], "creator": ["dm_reply", "dm_initiate"]}}}
];
for (const tag of agencyTagCatalog) {
  for (const rules of Object.values(tag.apps)) {
    Object.values(rules).forEach(Object.freeze);
    Object.freeze(rules);
  }
  Object.freeze(tag.apps);
  Object.freeze(tag);
}
Object.freeze(agencyTagCatalog);
const byId = new Map(agencyTagCatalog.map((tag) => [tag.id, tag]));

function agencyTagSupports(id, app, role = 'user', action) {
  const actions = byId.get(id)?.apps[app]?.[role];
  return !!actions?.length && (action === undefined || actions.includes(action));
}

function validateTags(value, label) {
  if (value === undefined) return;
  if (!Array.isArray(value) || value.length > 2 || new Set(value).size !== value.length ||
      value.some((id) => typeof id !== 'string' || !byId.has(id))) {
    throw new Error(`${label} agencyTags must contain at most two unique known tag IDs.`);
  }
}

/** Validate fields before normalizers can drop malformed authored data. */
function validateAccountAgency(app, account) {
  if (account.accountRole !== undefined &&
      (!['fotogram', 'onlyfriends'].includes(app) || !['user', 'creator'].includes(account.accountRole))) {
    throw new Error(`${app} accountRole must be user or creator on a social account.`);
  }
  validateTags(account.agencyTags, app);
  for (const id of account.agencyTags ?? []) {
    if (!agencyTagSupports(id, app, account.accountRole ?? 'user')) {
      const role = account.accountRole ?? 'user';
      const supportedRoles = Object.keys(byId.get(id)?.apps[app] ?? {});
      const alternatives = agencyTagCatalog.filter((tag) => agencyTagSupports(tag.id, app, role)).slice(0, 3).map((tag) => tag.id);
      throw new Error(`${app} agencyTags: ${id} does not support this app and account role. Effective accountRole: ${role}${account.accountRole === undefined ? ' (default)' : ''}. ${id} supports ${app} roles: ${supportedRoles.join(', ') || 'none'}. Choose a compatible character tag and app subset; compatible examples for this role: ${alternatives.join(', ') || 'none'}. Preserve the intended account role; do not change it just to fit a tag. Update character tags and all enabled app assignments together.`);
    }
  }
}

function validateCharacterAgency(character) {
  validateTags(character.agencyTags, 'Character');
  const tags = character.agencyTags ?? [];
  for (const [app, account] of Object.entries(character.apps ?? {})) {
    if (!account || typeof account !== 'object' || Array.isArray(account)) continue;
    validateAccountAgency(app, account);
    if ((account.agencyTags ?? []).some((id) => !tags.includes(id))) {
      throw new Error(`${app} agencyTags must be a subset of character agencyTags.`);
    }
    if (tags.length && account.enabled && !account.agencyTags?.length) {
      throw new Error(`${app} requires an explicit compatible agencyTags selection for a tagged character.`);
    }
  }
}

module.exports = { agencyTagCatalog, agencyTagSupports, validateAccountAgency, validateCharacterAgency };
